#ifndef SYNC_CLIENT_H
#define SYNC_CLIENT_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes for C API functions
 */
typedef enum CSyncResult {
  Success = 0,
  ErrorInvalidInput = -1,
  ErrorConnection = -2,
  ErrorDatabase = -3,
  ErrorSerialization = -4,
  ErrorUnknown = -99,
} CSyncResult;

/**
 * Event types that can be emitted by the sync client
 */
typedef enum EventType {
  /**
   * A new document was created (local or from sync)
   */
  DocumentCreated = 0,
  /**
   * An existing document was updated (local or from sync)
   */
  DocumentUpdated = 1,
  /**
   * A document was deleted (local or from sync)
   */
  DocumentDeleted = 2,
  /**
   * Synchronization process started
   */
  SyncStarted = 3,
  /**
   * Synchronization completed successfully
   */
  SyncCompleted = 4,
  /**
   * An error occurred during synchronization
   */
  SyncError = 5,
  /**
   * A conflict was detected between document versions
   */
  ConflictDetected = 6,
  /**
   * Connection to server was lost
   */
  ConnectionLost = 7,
  /**
   * A connection attempt was made to the server
   */
  ConnectionAttempted = 8,
  /**
   * Successfully connected to the server
   */
  ConnectionSucceeded = 9,
} EventType;

/**
 * Opaque handle to a SyncEngine instance
 */
typedef struct CSyncEngine CSyncEngine;

/**
 * Event data structure passed to C/C++ callbacks
 *
 * Contains all relevant information about the event. Not all fields are populated
 * for all event types - check the event_type to determine which fields are valid.
 */
typedef struct EventData {
  /**
   * Type of event that occurred
   */
  enum EventType event_type;
  /**
   * Document UUID (may be null for non-document events)
   */
  const char *document_id;
  /**
   * Document title (may be null)
   */
  const char *title;
  /**
   * Document content as JSON string (may be null)
   */
  const char *content;
  /**
   * Error message (only for error events, may be null)
   */
  const char *error;
  /**
   * Numeric data (e.g., sync count for SYNC_COMPLETED)
   */
  uint64_t numeric_data;
  /**
   * Boolean data (e.g., connection state for CONNECTION_STATE_CHANGED)
   */
  bool boolean_data;
} EventData;

/**
 * C-compatible callback function type for event notifications
 *
 * # Parameters
 *
 * * `event` - Pointer to event data (valid only during callback execution)
 * * `context` - User-defined context pointer passed during registration
 *
 * # Safety
 *
 * The event pointer is only valid during the callback execution.
 * Do not store or access it after the callback returns.
 * String pointers in the event data are temporary and will be freed
 * after the callback returns. Copy them if you need to retain the data.
 */
typedef void (*EventCallback)(const struct EventData *event, void *context);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new sync engine instance
 *
 * # Arguments
 * * `database_url` - SQLite database URL (e.g., "sqlite:client.db?mode=rwc")
 * * `server_url` - WebSocket server URL (e.g., "ws://localhost:8080/ws")
 * * `auth_token` - Authentication token
 * * `user_identifier` - User identifier (email or username)
 *
 * # Returns
 * * Pointer to CSyncEngine on success, null on failure
 */
struct CSyncEngine *sync_engine_create(const char *database_url,
                                       const char *server_url,
                                       const char *auth_token,
                                       const char *user_identifier);

/**
 * Destroy a sync engine instance and free memory
 */
void sync_engine_destroy(struct CSyncEngine *engine);

/**
 * Create a new document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `title` - Document title
 * * `content_json` - Document content as JSON string
 * * `out_document_id` - Output buffer for document ID (must be at least 37 chars)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 */
enum CSyncResult sync_engine_create_document(struct CSyncEngine *engine,
                                             const char *title,
                                             const char *content_json,
                                             char *out_document_id);

/**
 * Update an existing document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to update
 * * `content_json` - New document content as JSON string
 *
 * # Returns
 * * CSyncResult indicating success or failure
 */
enum CSyncResult sync_engine_update_document(struct CSyncEngine *engine,
                                             const char *document_id,
                                             const char *content_json);

/**
 * Delete a document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to delete
 *
 * # Returns
 * * CSyncResult indicating success or failure
 */
enum CSyncResult sync_engine_delete_document(struct CSyncEngine *engine, const char *document_id);

/**
 * Free a C string allocated by this library
 */
void sync_string_free(char *s);

/**
 * Get library version string
 */
char *sync_get_version(void);

/**
 * Register an event callback with optional event type filter
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for events
 * * `context` - User-defined context pointer passed to callback
 * * `event_filter` - Optional event type filter (-1 for all events)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 */
enum CSyncResult sync_engine_register_event_callback(struct CSyncEngine *engine,
                                                     EventCallback callback,
                                                     void *context,
                                                     int32_t event_filter);

/**
 * Process all queued events on the current thread
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_processed_count` - Output pointer for number of events processed (optional)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Important
 * This function MUST be called on the same thread where callbacks were registered.
 * Events are queued from any thread but only processed on the callback thread.
 */
enum CSyncResult sync_engine_process_events(struct CSyncEngine *engine,
                                            uint32_t *out_processed_count);

/**
 * Trigger a test event (for development/testing purposes)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `event_type` - Event type to emit (0-7)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Event Types
 * * 0 - DocumentCreated
 * * 1 - DocumentUpdated
 * * 2 - DocumentDeleted
 * * 3 - SyncStarted
 * * 4 - SyncCompleted
 * * 5 - SyncError
 * * 6 - ConflictDetected
 * * 7 - ConnectionLost
 * * 8 - ConnectionAttempted
 * * 9 - ConnectionSucceeded
 */
enum CSyncResult sync_engine_emit_test_event(struct CSyncEngine *engine, int32_t event_type);

/**
 * Trigger multiple test events in sequence (for stress testing callbacks)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `count` - Number of events to emit (1-100)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 */
enum CSyncResult sync_engine_emit_test_event_burst(struct CSyncEngine *engine, int32_t count);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* SYNC_CLIENT_H */
