/* JSON Database Sync Client C API */

#ifndef SYNC_CLIENT_H
#define SYNC_CLIENT_H

#pragma once

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace SyncClient {
#endif  // __cplusplus

/**
 * Event types that can be emitted by the sync client
 */
typedef enum EventType {
  /**
   * A new document was created (local or from sync)
   */
  DOCUMENT_CREATED = 0,
  /**
   * An existing document was updated (local or from sync)
   */
  DOCUMENT_UPDATED = 1,
  /**
   * A document was deleted (local or from sync)
   */
  DOCUMENT_DELETED = 2,
  /**
   * Synchronization process started
   */
  SYNC_STARTED = 3,
  /**
   * Synchronization completed successfully
   */
  SYNC_COMPLETED = 4,
  /**
   * An error occurred during synchronization
   */
  SYNC_ERROR = 5,
  /**
   * A conflict was detected between document versions
   */
  CONFLICT_DETECTED = 6,
  /**
   * Connection to server was lost
   */
  CONNECTION_LOST = 7,
  /**
   * A connection attempt was made to the server
   */
  CONNECTION_ATTEMPTED = 8,
  /**
   * Successfully connected to the server
   */
  CONNECTION_SUCCEEDED = 9,
} EventType;

/**
 * Result codes for C API functions
 */
typedef enum SyncResult {
  SUCCESS = 0,
  ERROR_INVALID_INPUT = -1,
  ERROR_CONNECTION = -2,
  ERROR_DATABASE = -3,
  ERROR_SERIALIZATION = -4,
  ERROR_UNKNOWN = -99,
} SyncResult;

typedef struct SyncEngine SyncEngine;

/**
 * Document event callback for DocumentCreated, DocumentUpdated, DocumentDeleted
 *
 * # Parameters
 * * `event_type` - The specific document event type
 * * `document_id` - UUID of the document (always non-null)
 * * `title` - Document title (null for Deleted events)
 * * `content` - Full document JSON (null for Deleted events)
 * * `context` - User-defined context pointer
 */
typedef void (*DocumentEventCallback)(enum EventType event_type,
                                      const char *document_id,
                                      const char *title,
                                      const char *content,
                                      void *context);

/**
 * Sync event callback for SyncStarted, SyncCompleted
 *
 * # Parameters
 * * `event_type` - SyncStarted or SyncCompleted
 * * `document_count` - Number of documents synced (0 for SyncStarted)
 * * `context` - User-defined context pointer
 */
typedef void (*SyncEventCallback)(enum EventType event_type, uint64_t document_count, void *context);

/**
 * Error event callback for SyncError
 *
 * # Parameters
 * * `event_type` - Always SyncError
 * * `error` - Error message (always non-null)
 * * `context` - User-defined context pointer
 */
typedef void (*ErrorEventCallback)(enum EventType event_type, const char *error, void *context);

/**
 * Connection event callback for ConnectionLost, ConnectionAttempted, ConnectionSucceeded
 *
 * # Parameters
 * * `event_type` - The connection event type
 * * `connected` - true if connected (valid for Lost/Succeeded), false otherwise
 * * `attempt_number` - Reconnection attempt number (valid for ConnectionAttempted)
 * * `context` - User-defined context pointer
 */
typedef void (*ConnectionEventCallback)(enum EventType event_type,
                                        bool connected,
                                        uint32_t attempt_number,
                                        void *context);

/**
 * Conflict event callback for ConflictDetected
 *
 * # Parameters
 * * `event_type` - Always ConflictDetected
 * * `document_id` - UUID of the conflicted document (always non-null)
 * * `winning_content` - Content of the winning version (always non-null)
 * * `losing_content` - Content of the losing version (may be null)
 * * `context` - User-defined context pointer
 */
typedef void (*ConflictEventCallback)(enum EventType event_type,
                                      const char *document_id,
                                      const char *winning_content,
                                      const char *losing_content,
                                      void *context);

/**
 * Document structure for C API
 */
typedef struct Document {
  char *id;
  char *title;
  char *content;
  int64_t sync_revision;
} Document;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new sync engine instance
 *
 * # Arguments
 * * `database_url` - SQLite database URL (e.g., "sqlite:client.db?mode=rwc")
 * * `server_url` - WebSocket server URL (e.g., "ws://localhost:8080/ws")
 * * `email` - User email address
 * * `api_key` - Application API key (rpa_ prefix)
 * * `api_secret` - Application API secret (rps_ prefix)
 *
 * # Returns
 * * Pointer to SyncEngine on success, null on failure
 *
 * # Safety
 * Caller must ensure all pointers are valid, non-null C strings
 */
struct SyncEngine *sync_engine_create(const char *database_url,
                                      const char *server_url,
                                      const char *email,
                                      const char *api_key,
                                      const char *api_secret);

/**
 * Destroy a sync engine instance and free memory
 *
 * # Safety
 * Caller must ensure engine pointer was created by sync_engine_create and hasn't been freed
 */
void sync_engine_destroy(struct SyncEngine *engine);

/**
 * Create a new document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `content_json` - Document content as JSON string (should include any title as part of the JSON)
 * * `out_document_id` - Output buffer for document ID (must be at least 37 chars)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, content_json is a valid C string, and out_document_id has space for 37 bytes
 */
enum SyncResult sync_engine_create_document(struct SyncEngine *engine,
                                            const char *content_json,
                                            char *out_document_id);

/**
 * Update an existing document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to update
 * * `content_json` - New document content as JSON string
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid and both document_id and content_json are valid C strings
 */
enum SyncResult sync_engine_update_document(struct SyncEngine *engine,
                                            const char *document_id,
                                            const char *content_json);

/**
 * Delete a document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to delete
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid and document_id is a valid C string
 */
enum SyncResult sync_engine_delete_document(struct SyncEngine *engine, const char *document_id);

/**
 * Free a C string allocated by this library
 *
 * # Safety
 * Caller must ensure the string was allocated by this library and hasn't been freed
 */
void sync_string_free(char *s);

/**
 * Get library version string
 */
char *sync_get_version(void);

/**
 * Register a callback for document events (Created, Updated, Deleted)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for document events
 * * `context` - User-defined context pointer passed to callback
 * * `event_filter` - Optional filter: 0=Created, 1=Updated, 2=Deleted, -1=all document events
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum SyncResult sync_engine_register_document_callback(struct SyncEngine *engine,
                                                       DocumentEventCallback callback,
                                                       void *context,
                                                       int32_t event_filter);

/**
 * Register a callback for sync events (Started, Completed)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for sync events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum SyncResult sync_engine_register_sync_callback(struct SyncEngine *engine,
                                                   SyncEventCallback callback,
                                                   void *context);

/**
 * Register a callback for error events (SyncError)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for error events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum SyncResult sync_engine_register_error_callback(struct SyncEngine *engine,
                                                    ErrorEventCallback callback,
                                                    void *context);

/**
 * Register a callback for connection events (Lost, Attempted, Succeeded)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for connection events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum SyncResult sync_engine_register_connection_callback(struct SyncEngine *engine,
                                                         ConnectionEventCallback callback,
                                                         void *context);

/**
 * Register a callback for conflict events (ConflictDetected)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for conflict events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum SyncResult sync_engine_register_conflict_callback(struct SyncEngine *engine,
                                                       ConflictEventCallback callback,
                                                       void *context);

/**
 * Process all queued events on the current thread
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_processed_count` - Output pointer for number of events processed (optional)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Important
 * This function MUST be called on the same thread where callbacks were registered.
 * Events are queued from any thread but only processed on the callback thread.
 *
 * # Safety
 * Caller must ensure engine is valid and out_processed_count points to valid memory (if not null)
 */
enum SyncResult sync_engine_process_events(struct SyncEngine *engine,
                                           uint32_t *out_processed_count);

/**
 * Get a document by ID
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID as UUID string
 * * `out_content` - Output pointer for document JSON content (caller must free with sync_string_free)
 *
 * # Returns
 * * SyncResult::Success if document found and content returned
 * * SyncResult::ErrorInvalidInput if document not found or invalid ID
 *
 * # Safety
 * Caller must ensure engine is valid, document_id is a valid C string, and out_content is a valid pointer
 */
enum SyncResult sync_engine_get_document(struct SyncEngine *engine,
                                         const char *document_id,
                                         char **out_content);

/**
 * Get all documents as a JSON array
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_documents` - Output pointer for JSON array of documents (caller must free with sync_string_free)
 *
 * # Returns
 * * SyncResult::Success with JSON array (empty array [] if no documents)
 *
 * # Safety
 * Caller must ensure engine is valid and out_documents is a valid pointer
 */
enum SyncResult sync_engine_get_all_documents(struct SyncEngine *engine,
                                              char **out_documents);

/**
 * Get the count of local documents
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_count` - Output pointer for document count
 *
 * # Returns
 * * SyncResult::Success with count written to out_count
 *
 * # Safety
 * Caller must ensure engine is valid and out_count is a valid pointer
 */
enum SyncResult sync_engine_count_documents(struct SyncEngine *engine, uint64_t *out_count);

/**
 * Check if the sync engine is connected to the server
 *
 * # Arguments
 * * `engine` - Sync engine instance
 *
 * # Returns
 * * true if connected, false if disconnected or engine is null
 *
 * # Safety
 * Caller must ensure engine was created by sync_engine_create
 */
bool sync_engine_is_connected(struct SyncEngine *engine);

/**
 * Get the count of documents pending sync to server
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_count` - Output pointer for pending document count
 *
 * # Returns
 * * SyncResult::Success with count written to out_count
 *
 * # Safety
 * Caller must ensure engine is valid and out_count is a valid pointer
 */
enum SyncResult sync_engine_count_pending_sync(struct SyncEngine *engine, uint64_t *out_count);

/**
 * Trigger a test event (for development/testing purposes)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `event_type` - Event type to emit (0-7)
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Event Types
 * * 0 - DocumentCreated
 * * 1 - DocumentUpdated
 * * 2 - DocumentDeleted
 * * 3 - SyncStarted
 * * 4 - SyncCompleted
 * * 5 - SyncError
 * * 6 - ConflictDetected
 * * 7 - ConnectionLost
 * * 8 - ConnectionAttempted
 * * 9 - ConnectionSucceeded
 *
 * # Safety
 * Caller must ensure engine is a valid pointer
 */
enum SyncResult sync_engine_emit_test_event(struct SyncEngine *engine, int32_t event_type);

/**
 * Trigger multiple test events in sequence (for stress testing callbacks)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `count` - Number of events to emit (1-100)
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is a valid pointer
 */
enum SyncResult sync_engine_emit_test_event_burst(struct SyncEngine *engine, int32_t count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace SyncClient
#endif  // __cplusplus

#endif  /* SYNC_CLIENT_H */
