/* Replicant - Offline-first Document Sync C API */

#ifndef REPLICANT_H
#define REPLICANT_H

#pragma once

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace replicant {
#endif  // __cplusplus

/**
 * Event types that can be emitted by the sync client
 */
typedef enum ReplicantEventType {
  /**
   * A new document was created (local or from sync)
   */
  DocumentCreated = 0,
  /**
   * An existing document was updated (local or from sync)
   */
  DocumentUpdated = 1,
  /**
   * A document was deleted (local or from sync)
   */
  DocumentDeleted = 2,
  /**
   * Synchronization process started
   */
  SyncStarted = 3,
  /**
   * Synchronization completed successfully
   */
  SyncCompleted = 4,
  /**
   * An error occurred during synchronization
   */
  SyncError = 5,
  /**
   * A conflict was detected between document versions
   */
  ConflictDetected = 6,
  /**
   * Connection to server was lost
   */
  ConnectionLost = 7,
  /**
   * A connection attempt was made to the server
   */
  ConnectionAttempted = 8,
  /**
   * Successfully connected to the server
   */
  ConnectionSucceeded = 9,
} ReplicantEventType;

/**
 * Result codes for C API functions
 */
typedef enum ReplicantSyncResult {
  Success = 0,
  ErrorInvalidInput = -1,
  ErrorConnection = -2,
  ErrorDatabase = -3,
  ErrorSerialization = -4,
  ErrorUnknown = -99,
} ReplicantSyncResult;

/**
 * Opaque handle to a Replicant client instance
 */
typedef struct Replicant Replicant;

/**
 * Document event callback for DocumentCreated, DocumentUpdated, DocumentDeleted
 *
 * # Parameters
 * * `event_type` - The specific document event type
 * * `document_id` - UUID of the document (always non-null)
 * * `title` - Document title (null for Deleted events)
 * * `content` - Full document JSON (null for Deleted events)
 * * `context` - User-defined context pointer
 */
typedef void (*DocumentEventCallback)(enum ReplicantEventType event_type,
                                      const char *document_id,
                                      const char *title,
                                      const char *content,
                                      void *context);

/**
 * Sync event callback for SyncStarted, SyncCompleted
 *
 * # Parameters
 * * `event_type` - SyncStarted or SyncCompleted
 * * `document_count` - Number of documents synced (0 for SyncStarted)
 * * `context` - User-defined context pointer
 */
typedef void (*SyncEventCallback)(enum ReplicantEventType event_type,
                                  uint64_t document_count,
                                  void *context);

/**
 * Error event callback for SyncError
 *
 * # Parameters
 * * `event_type` - Always SyncError
 * * `error` - Error message (always non-null)
 * * `context` - User-defined context pointer
 */
typedef void (*ErrorEventCallback)(enum ReplicantEventType event_type,
                                   const char *error,
                                   void *context);

/**
 * Connection event callback for ConnectionLost, ConnectionAttempted, ConnectionSucceeded
 *
 * # Parameters
 * * `event_type` - The connection event type
 * * `connected` - true if connected (valid for Lost/Succeeded), false otherwise
 * * `attempt_number` - Reconnection attempt number (valid for ConnectionAttempted)
 * * `context` - User-defined context pointer
 */
typedef void (*ConnectionEventCallback)(enum ReplicantEventType event_type,
                                        bool connected,
                                        uint32_t attempt_number,
                                        void *context);

/**
 * Conflict event callback for ConflictDetected
 *
 * # Parameters
 * * `event_type` - Always ConflictDetected
 * * `document_id` - UUID of the conflicted document (always non-null)
 * * `winning_content` - Content of the winning version (always non-null)
 * * `losing_content` - Content of the losing version (may be null)
 * * `context` - User-defined context pointer
 */
typedef void (*ConflictEventCallback)(enum ReplicantEventType event_type,
                                      const char *document_id,
                                      const char *winning_content,
                                      const char *losing_content,
                                      void *context);

/**
 * Document structure for C API
 */
typedef struct Document {
  char *id;
  char *title;
  char *content;
  int64_t sync_revision;
} Document;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new sync engine instance
 *
 * # Arguments
 * * `database_url` - SQLite database URL (e.g., "sqlite:client.db?mode=rwc")
 * * `server_url` - WebSocket server URL (e.g., "ws://localhost:8080/ws")
 * * `email` - User email address
 * * `api_key` - Application API key (rpa_ prefix)
 * * `api_secret` - Application API secret (rps_ prefix)
 *
 * # Returns
 * * Pointer to SyncEngine on success, null on failure
 *
 * # Safety
 * Caller must ensure all pointers are valid, non-null C strings
 */
struct Replicant *replicant_create(const char *database_url,
                                   const char *server_url,
                                   const char *email,
                                   const char *api_key,
                                   const char *api_secret);

/**
 * Destroy a sync engine instance and free memory
 *
 * # Safety
 * Caller must ensure engine pointer was created by replicant_create and hasn't been freed
 */
void replicant_destroy(struct Replicant *engine);

/**
 * Create a new document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `content_json` - Document content as JSON string (should include any title as part of the JSON)
 * * `out_document_id` - Output buffer for document ID (must be at least 37 chars)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, content_json is a valid C string, and out_document_id has space for 37 bytes
 */
enum ReplicantSyncResult replicant_create_document(struct Replicant *engine,
                                                   const char *content_json,
                                                   char *out_document_id);

/**
 * Create a new document with a specified ID
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - UUID string to use as the document ID
 * * `content_json` - Document content as JSON string
 *
 * # Returns
 * * `SyncResult::Success` - Document created successfully
 * * `SyncResult::ErrorInvalidInput` - Invalid UUID format or null pointers
 * * `SyncResult::ErrorSerialization` - Invalid JSON content
 * * `SyncResult::ErrorDatabase` - Database operation failed
 * * `SyncResult::ErrorConnection` - Sync to server failed (document saved locally)
 *
 * # Note
 * If a document with the specified ID already exists, it will be overwritten (upsert behavior).
 * Use this for ID preservation during data migration or import scenarios.
 *
 * # Safety
 * Caller must ensure engine is valid, document_id and content_json are valid C strings
 */
enum ReplicantSyncResult replicant_create_document_with_id(struct Replicant *engine,
                                                           const char *document_id,
                                                           const char *content_json);

/**
 * Update an existing document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to update
 * * `content_json` - New document content as JSON string
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid and both document_id and content_json are valid C strings
 */
enum ReplicantSyncResult replicant_update_document(struct Replicant *engine,
                                                   const char *document_id,
                                                   const char *content_json);

/**
 * Delete a document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to delete
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid and document_id is a valid C string
 */
enum ReplicantSyncResult replicant_delete_document(struct Replicant *engine,
                                                   const char *document_id);

/**
 * Free a C string allocated by this library
 *
 * # Safety
 * Caller must ensure the string was allocated by this library and hasn't been freed
 */
void replicant_string_free(char *s);

/**
 * Get library version string
 */
char *replicant_get_version(void);

/**
 * Register a callback for document events (Created, Updated, Deleted)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for document events
 * * `context` - User-defined context pointer passed to callback
 * * `event_filter` - Optional filter: 0=Created, 1=Updated, 2=Deleted, -1=all document events
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_document_callback(struct Replicant *engine,
                                                              DocumentEventCallback callback,
                                                              void *context,
                                                              int32_t event_filter);

/**
 * Register a callback for sync events (Started, Completed)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for sync events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_sync_callback(struct Replicant *engine,
                                                          SyncEventCallback callback,
                                                          void *context);

/**
 * Register a callback for error events (SyncError)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for error events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_error_callback(struct Replicant *engine,
                                                           ErrorEventCallback callback,
                                                           void *context);

/**
 * Register a callback for connection events (Lost, Attempted, Succeeded)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for connection events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_connection_callback(struct Replicant *engine,
                                                                ConnectionEventCallback callback,
                                                                void *context);

/**
 * Register a callback for conflict events (ConflictDetected)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for conflict events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_conflict_callback(struct Replicant *engine,
                                                              ConflictEventCallback callback,
                                                              void *context);

/**
 * Process all queued events on the current thread
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_processed_count` - Output pointer for number of events processed (optional)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Important
 * This function MUST be called on the same thread where callbacks were registered.
 * Events are queued from any thread but only processed on the callback thread.
 *
 * # Safety
 * Caller must ensure engine is valid and out_processed_count points to valid memory (if not null)
 */
enum ReplicantSyncResult replicant_process_events(struct Replicant *engine,
                                                  uint32_t *out_processed_count);

/**
 * Get a document by ID
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID as UUID string
 * * `out_content` - Output pointer for document JSON content (caller must free with replicant_string_free)
 *
 * # Returns
 * * SyncResult::Success if document found and content returned
 * * SyncResult::ErrorInvalidInput if document not found or invalid ID
 *
 * # Safety
 * Caller must ensure engine is valid, document_id is a valid C string, and out_content is a valid pointer
 */
enum ReplicantSyncResult replicant_get_document(struct Replicant *engine,
                                                const char *document_id,
                                                char **out_content);

/**
 * Get all documents as a JSON array
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_documents` - Output pointer for JSON array of documents (caller must free with replicant_string_free)
 *
 * # Returns
 * * SyncResult::Success with JSON array (empty array [] if no documents)
 *
 * # Safety
 * Caller must ensure engine is valid and out_documents is a valid pointer
 */
enum ReplicantSyncResult replicant_get_all_documents(struct Replicant *engine,
                                                     char **out_documents);

/**
 * Get the count of local documents
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_count` - Output pointer for document count
 *
 * # Returns
 * * SyncResult::Success with count written to out_count
 *
 * # Safety
 * Caller must ensure engine is valid and out_count is a valid pointer
 */
enum ReplicantSyncResult replicant_count_documents(struct Replicant *engine, uint64_t *out_count);

/**
 * Check if the sync engine is connected to the server
 *
 * # Arguments
 * * `engine` - Sync engine instance
 *
 * # Returns
 * * true if connected, false if disconnected or engine is null
 *
 * # Safety
 * Caller must ensure engine was created by replicant_create
 */
bool replicant_is_connected(struct Replicant *engine);

/**
 * Get the count of documents pending sync to server
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_count` - Output pointer for pending document count
 *
 * # Returns
 * * SyncResult::Success with count written to out_count
 *
 * # Safety
 * Caller must ensure engine is valid and out_count is a valid pointer
 */
enum ReplicantSyncResult replicant_count_pending_sync(struct Replicant *engine,
                                                      uint64_t *out_count);

/**
 * Configure which JSON paths to index for full-text search
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `paths_json` - JSON array of JSON paths to index (e.g., '["$.body", "$.notes"]')
 *
 * # Returns
 * * SyncResult::Success if configuration succeeded
 * * SyncResult::ErrorInvalidInput if paths_json is invalid
 * * SyncResult::ErrorDatabase if index rebuild fails
 *
 * # Note
 * This replaces any existing configuration and rebuilds the search index.
 *
 * # Safety
 * Caller must ensure engine is valid and paths_json is a valid C string
 */
enum ReplicantSyncResult replicant_configure_search(struct Replicant *engine,
                                                    const char *paths_json);

/**
 * Search documents using FTS5 full-text search
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `query` - FTS5 query string (e.g., "music", "tun*", "\"exact phrase\"")
 * * `limit` - Maximum number of results (0 for default of 100)
 * * `out_documents` - Output pointer for JSON array of matching documents
 *
 * # Returns
 * * SyncResult::Success with JSON array in out_documents
 * * SyncResult::ErrorInvalidInput if query is invalid
 * * SyncResult::ErrorDatabase if search fails
 *
 * # FTS5 Query Syntax
 * * Simple terms: "music" matches documents containing "music"
 * * Prefix: "tun*" matches "tuning", "tune", etc.
 * * Phrase: "\"equal temperament\"" matches exact phrase
 * * Boolean: "music AND theory", "piano OR keyboard"
 * * Column filter: "title:beethoven" searches only title field
 *
 * # Safety
 * Caller must ensure engine is valid, query is a valid C string,
 * and out_documents is a valid pointer. Caller must free result with replicant_string_free.
 */
enum ReplicantSyncResult replicant_search_documents(struct Replicant *engine,
                                                    const char *query,
                                                    uint32_t limit,
                                                    char **out_documents);

/**
 * Rebuild the full-text search index
 *
 * # Arguments
 * * `engine` - Replicant client instance
 *
 * # Returns
 * * SyncResult::Success if rebuild succeeded
 * * SyncResult::ErrorDatabase if rebuild fails
 *
 * # Note
 * This is called automatically by replicant_configure_search, but can be
 * called manually if needed (e.g., after bulk document imports).
 *
 * # Safety
 * Caller must ensure engine is valid
 */
enum ReplicantSyncResult replicant_rebuild_search_index(struct Replicant *engine);

/**
 * Trigger a test event (for development/testing purposes)
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `event_type` - Event type to emit (0-7)
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Event Types
 * * 0 - DocumentCreated
 * * 1 - DocumentUpdated
 * * 2 - DocumentDeleted
 * * 3 - SyncStarted
 * * 4 - SyncCompleted
 * * 5 - SyncError
 * * 6 - ConflictDetected
 * * 7 - ConnectionLost
 * * 8 - ConnectionAttempted
 * * 9 - ConnectionSucceeded
 *
 * # Safety
 * Caller must ensure engine is a valid pointer
 */
enum ReplicantSyncResult replicant_emit_test_event(struct Replicant *engine, int32_t event_type);

/**
 * Trigger multiple test events in sequence (for stress testing callbacks)
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `count` - Number of events to emit (1-100)
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is a valid pointer
 */
enum ReplicantSyncResult replicant_emit_test_event_burst(struct Replicant *engine, int32_t count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace replicant
#endif  // __cplusplus

#endif  /* REPLICANT_H */
